version: '3'

services:
 rabbitmq:
  image: rabbitmq:3.7.4-management
  hostname: rabbitmq
  ports:
   - "5672:5672"
   - "15672:15672"
  environment:
   RABBITMQ_DEFAULT_USER: guest
   RABBITMQ_DEFAULT_PASS: guest
  networks:
   - meminator

 eurekaserver:
  image: dakipej/serviceregistry
  ports: 
   - 8761:8761
  networks:
   - meminator

 usermodule:
  image: dakipej/usermodule
  depends_on:
   - mysql
   - eurekaserver
   - rabbitmq
  ports:
   - 8083:8083
  environment:
   #dodano za rabbitmq
   SPRING_RABBITMQ_HOST: rabbitmq
   #RABBIT_HOST: rabbitmq
   #Dodano kako bi aplikacija mogla koristiti mysql servis
   SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/userModuleDB'
   #Dodano za eureku
   SPRING_APPLICATION_NAME: userModule
   SPRING_PROFILES_ACTIVE: enableEureka
   EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
   EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
  networks:
   - meminator

 #MYSQL podesen, ne diraj!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 mysql:
  image: mysql:5.6
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=userModuleDB
   - MYSQL_USER=demo_user
   - MYSQL_PASSWORD=demo_pass
  networks: 
   - meminator

networks:
 meminator:
  driver: bridge