FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE
ADD ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

#FROM java:8
#ARG JAR_FILE
#ADD ${JAR_FILE} app.jar
#ADD wrapper.sh wrapper.sh
#RUN bash -c 'chmod +x /wrapper.sh'
#RUN bash -c 'touch /app.jar'
#ENTRYPOINT ["/bin/bash", "/wrapper.sh"]

#FROM java:8
#ARG JAR_FILE
#ADD ${JAR_FILE} app.jar
#RUN bash -c 'touch /app.jar'
#ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=container","-jar","/app.jar"]

